GET http://127.0.0.1:5000
Content-Type: application/json

### 
POST http://127.0.0.1:5000/doar
Content-Type: application/json

{
  "title": "Um verão na Itália",
  "category": "Romance",
  "author": "Carrie Elks",
  "image_url": "https://i0.wp.com/blog.skeelo.com/wp-content/uploads/2023/06/um-verao-na-italia.png"
}

### 
GET http://127.0.0.1:5000/list-livros

### 
DELETE http://127.0.0.1:5000/livros/1
