GET http://127.0.0.1:5000
Content-Type: application/json

### 
POST http://127.0.0.1:5000/doar
Content-Type: application/json

{
  "title": "O senhor dos aneis",
  "category": "Fantasia",
  "author": "J. R. R. Tolkien",
  "image_url": "https://http2.mlstatic.com/D_NQ_NP_921355-MLU74113001742_012024-O.webp"
}

### 
GET http://127.0.0.1:5000/list-livros

### 
DELETE http://127.0.0.1:5000/livros/4
