#  Necessário da extensão REST CLIENT para funcionar
# Quando tiver instalada acima da HTTP link aparecerá `Send Request` só clicar com o mouse pressionando a tecla CTRL.

GET http://127.0.0.1:5000
Content-Type: application/json

### 
POST http://127.0.0.1:5000/doar
Content-Type: application/json

{
  "title": "Alice no País das Maravilhas",
  "category": "Fantasia",
  "author": "Lewis Carroll",
  "image_url": "https://http2.mlstatic.com/D_NQ_NP_921355-MLU74113001742_012024-O.webp"
}

### 
GET http://127.0.0.1:5000/list-livros

### 
PUT http://127.0.0.1:5000/livros/10
Content-Type: application/json

{
  "title": "Alice no País das Maravilhas AA",
  "category": "Fantasia AA",
  "author": "Lewis Carroll AA",
  "image_url": "https://http2.mlstatic.com/D_NQ_NP_921355-MLU74113001742_012024-O.webp"
}


### 
DELETE http://127.0.0.1:5000/livros/7
